name: Master - Build, Test, Pack & Publish

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./shufl-web
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
          
    - name: Setup Node ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install modules and Build for Production
      run: |
        npm i
        npm run build:prod
        
    - name: Run Tests and Generate Coverage Report
      run: npm run test
      
    - name: Deploy (Firebase)
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_WEBENV_SHUFL }}'
        projectId: webenv-shufl
        entryPoint: ./shufl-web
        channelId: live
      env:
        FIREBASE_CLI_PREVIEWS: hostingchannels
        
    - name: Publish Coverage
      uses: codacy/codacy-coverage-reporter-action@0.2.0
      with:
        project-token: ${{ secrets.CODACY_TOKEN }}
        coverage-reports: shufl-web/coverage/clover.xml
        
    - name: Archive Test Screenshots
      uses: actions/upload-artifact@v2
      if: ${{ failure() }}
      with:
        name: Screenshots
        path: shufl-web/cypress/screenshots/
        retention-days: 5
        
    - name: Archive Test Videos
      uses: actions/upload-artifact@v2
      if: ${{ failure() }}
      with:
        name: Videos
        path: shufl-web/cypress/videos/
        retention-days: 5
